### ISSUE TITLE
How to understand  the loss (Formula 11)?

### ISSUE THREAD

**Issue by sh-qiangchen** [fannie1208/CaNet#3]
Hi, thanks for sharing the code.

I noticed that you used `def reg_loss()` to realize the KL-divergence for minimizing the differences between 𝑞𝜙(𝐸|𝐺) and uniform
distribution as much as possible.
![reg](https://github.com/user-attachments/assets/0bb2234d-e94e-48f0-b379-8e39b673e16b)

However, there are two confusion questions. 
(1) The code is inconsistent with the Formula 11.
(2) Why add a **_negative sign_** before KL divergence in Formula 11.

**Comment by fannie1208** [comment]
Hi, thank you for your question.
As for the Formula 11, there's no negative sign before KL divergence. Thank you for pointing out the typo, and we will fix it in the updated PDF.
As for the code, in the implementation of KL loss, there's no negative sign. And we omit the constant logK since it will not contribute to the gradient.

**Comment by sh-qiangchen** [comment]
Thanks for your reply, this is a great project!
